services:
  fastapi:
    build: .
    container_name: fastapi_service
    ports:
      - "8000:8000"
    command: uvicorn movie_api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

  streamlit:
    build: .
    container_name: streamlit_service
    ports:
      - "8501:8501"
    command: streamlit run movie_api/app.py --server.port 8501
    volumes:
      - .:/app
